server.port= 8080
spring.application.name=ecommerce.be

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ecommerce-data;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

paypal.client-id = Aen-X4Jix2CD_F3vslhM3qcpzhnKVTK7HfbeWN9dIW-BbQ5ssuF0OqUmTYkkqRM55zyNgbq5qy1vHPOH
paypal.secret = EHVs7l1j_uf7O8sYf9Q9SuHr4MimQrj9EUjPBpn9TDbv9AJYUSHAS6hYUO30_B20iH-vTfh36eLhxFVL
paypal.mode = sandbox